// <auto-generated />
using System;
using C44_G00_EF05_Demo.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace C44_G00_EF05_Demo.Migrations
{
    [DbContext(typeof(EmpDbContext))]
    [Migration("20250901193945_TPT")]
    partial class TPT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("C44_G00_EF05_Demo.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("C44_G00_EF05_Demo.Models.FTEmployee", b =>
                {
                    b.HasBaseType("C44_G00_EF05_Demo.Models.Employee");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.ToTable("FTEmployees", (string)null);
                });

            modelBuilder.Entity("C44_G00_EF05_Demo.Models.PTEmployee", b =>
                {
                    b.HasBaseType("C44_G00_EF05_Demo.Models.Employee");

                    b.Property<int>("CountOfHours")
                        .HasColumnType("int");

                    b.Property<decimal>("HourRate")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("PTEmployees", (string)null);
                });

            modelBuilder.Entity("C44_G00_EF05_Demo.Models.FTEmployee", b =>
                {
                    b.HasOne("C44_G00_EF05_Demo.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("C44_G00_EF05_Demo.Models.FTEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("C44_G00_EF05_Demo.Models.PTEmployee", b =>
                {
                    b.HasOne("C44_G00_EF05_Demo.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("C44_G00_EF05_Demo.Models.PTEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
